### ISSUE TITLE
Tracking issue for dependency upgrades

### ISSUE THREAD

**Issue by liquidnya** [fluid-queue/fluid-queue#131]
**Dependencies**

- [ ] Update `typescript` to `>=5.2` (`^5.2.2`).
  This is blocked by:
   - `eslint-plugin-jest` upgrades their transitive dependency of `@typescript-eslint/typescript-estree` to `>=6.4.0`.
  Changes needed:
  - [ ] Update dependency version of `eslint-plugin-jest`
  - [ ] Update dependency version of `typescript`
- [ ] Update `jest-chance` to `>=0.2.5` (`^0.2.5`).
  This is blocked by:
   - The [minimum supported node version](https://github.com/fluid-queue/fluid-queue/blob/develop/package.json#L88) of `fluid-queue`, since `jest-chance` requires node `>=19.0.0`.
   - The release of node 20 as an LTS version.
  Changes needed:
  - [ ] Update dependency version of `jest-chance`.
  - [ ] Update the minimum node version to either `>=19.0.0` or the LTS version of node 20 in `package.json`.
  - [ ] Update dependency version of `@types/node` to the minimum supported node version prefixed with `~`.
  - [ ] Update dependency version of `@tsconfig/node18` to the correct major version in its name and update the `"extends"` field of `tsconfig.json` and make sure to adjust `"compilerOptions"` too if needed.
  - [ ] Change the target version in `build.ts` to be the minimum node version.
  - [ ] Set `"globalSetup"` to `"./node_modules/jest-chance/dist/esm/index.js"` in `tests/jest.config.json` (or revert commit b9f8596ed3f6571db82368ff14ae9a197c1ed15d).

**Comment by liquidnya** [comment]
This task is fixed by #144.
